# Generated by Django 5.2.3 on 2025-08-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
                ('date_birth', models.DateField(db_column='dt_date_birth')),
                ('email', models.EmailField(db_column='tx_email', max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male')], db_column='tx_sex', max_length=10)),
                ('cpf', models.CharField(db_column='tx_cpf', max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
