# Generated by Django 5.2.5 on 2025-08-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='type_application',
            field=models.IntegerField(choices=[(1, 'Oral'), (2, 'Injetável')], db_column='cs_type_application'),
        ),
    ]
