# Generated by Django 5.2.3 on 2025-08-26 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(choices=[('O+', 'O+'), ('B+', 'B+'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('A+', 'A+'), ('A-', 'A-')], db_column='tx_name', default='O+', max_length=255)),
            ],
            options={
                'verbose_name': 'Blood Type',
                'verbose_name_plural': 'Blood Types',
                'db_table': 'blood_type',
            },
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
            ],
            options={
                'verbose_name': 'Health Insurance',
                'verbose_name_plural': 'Health Insurances',
                'db_table': 'health_insurance',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
                ('type_application', models.CharField(choices=[('2-', 'injectable'), ('1-', 'oral')], db_column='type_application', max_length=40)),
                ('type_dosage', models.CharField(choices=[('2-', '2mg'), ('1-', '1ml')], db_column='type_dosage', max_length=40)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=210)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('postal_code', models.CharField(db_column='tx_postal_code', max_length=8)),
                ('number_house', models.CharField(db_column='tx_number_house', max_length=10)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='hospital.user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('crm', models.CharField(db_column='tx_crm', max_length=120, unique=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='hospital.user')),
                ('specialization', models.ManyToManyField(db_table='specialization_medic', to='hospital.specialization')),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
                'db_table': 'medic',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('time_consultation', models.DateTimeField(db_column='datetime')),
                ('diagnosis', models.TextField(db_column='tx_diagnosis', max_length=255)),
                ('medic_attended', models.BooleanField(db_column='cs_medic_attended')),
                ('patient_attended', models.BooleanField(db_column='cs_patient_attended')),
                ('medic', models.ForeignKey(db_column='id_medic', on_delete=django.db.models.deletion.PROTECT, to='hospital.medic')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='MedicationConsultation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('dosage', models.IntegerField(db_column='dosage')),
                ('consultation', models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.CASCADE, to='hospital.consultation')),
                ('medication', models.ForeignKey(db_column='id_medication', on_delete=django.db.models.deletion.PROTECT, to='hospital.medication')),
            ],
            options={
                'verbose_name': 'Medication Consultation',
                'verbose_name_plural': 'Medication Consultations',
                'db_table': 'medication_consultation',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medication',
            field=models.ManyToManyField(through='hospital.MedicationConsultation', to='hospital.medication'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('weight', models.DecimalField(db_column='nb_weight', decimal_places=2, max_digits=5)),
                ('height', models.IntegerField(db_column='nb_height', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('blood_type', models.ForeignKey(db_column='id_blood_type', on_delete=django.db.models.deletion.PROTECT, to='hospital.bloodtype')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='hospital.user')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.PROTECT, to='hospital.patient'),
        ),
        migrations.CreateModel(
            name='PatientHealthInsurance',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('insurance_number', models.CharField(db_column='insurance_number', max_length=120)),
                ('type', models.CharField(choices=[('apartment', 'apartment'), ('nursery', 'nursery')], db_column='type', max_length=255)),
                ('waiting_period', models.DateField(db_column='dt_waiting_period')),
                ('health_insurance', models.ForeignKey(db_column='id_health_insurance', on_delete=django.db.models.deletion.PROTECT, to='hospital.healthinsurance')),
                ('patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Patient Health Insurance',
                'verbose_name_plural': 'Patients Health Insurances',
                'db_table': 'patient_health_insurance',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('number', models.CharField(db_column='tx_number', max_length=11, unique=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='hospital.user')),
            ],
            options={
                'verbose_name': 'Telephone',
                'verbose_name_plural': 'Telephones',
                'db_table': 'telephone',
            },
        ),
    ]
